apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: cspr-findings-job
  labels:
    cloud.googleapis.com/location: us-east1
spec:
  template:
    spec:
      taskCount: 1
      template:
        spec:
          serviceAccountName: cspr-prereq-cloudrun-sa@nu-cspr-assessment.iam.gserviceaccount.com
          containers:
          - image: us-east1-docker.pkg.dev/nu-cspr-assessment/customer-cspr-toolkit/cspr-toolkit-findings:latest
            env:
            - name: BQ_PROJECT
              value: "nu-cspr-assessment"
            - name: BQ_PROJECT_ID
              value: "nu-cspr-assessment"
            - name: BQ_BILLING_PROJECT
              value: "nu-cspr-assessment"
            - name: LOCATION
              value: "us-east1"
            - name: ORGANIZATION_ID
              value: "802070535070"
            - name: ORG_DOMAIN
              value: "nubank.com.br"
            - name: INCLUDE_LIST
              value: ""
            - name: EXCLUDE_LIST
              value: ""
            - name: BQDATASET_INVENTORY
              value: "cspr_cai"
            - name: BQDATASET_POLICYANALYZER
              value: "cspr_policy"
            - name: BQDATASET_EFFECTIVEORGPOLICY
              value: "cspr_policy"
            - name: BQDATASET_REC
              value: "cspr_rec"
            - name: BQDATASET_FINDING
              value: "cspr_finding"
            - name: BQDATASET_CLOUDIDENTITY
              value: "cspr_ci"
            resources:
              limits:
                cpu: "2000m"
                memory: "4Gi"
          timeoutSeconds: 3600
          maxRetries: 1
